---
- hosts: all
  remote_user: root
  tasks:
  - name: update OS
    yum:
      name: '*'
      state: latest
  - name: Set hostname
    hostname:
      name: "{{ cp_hostname_long }}"
  - name: Insert CP's loopback address into /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "127.0.0.1\t{{ ansible_fqdn }}\t{{ ansible_hostname }}"
  - name: Insert all CPs in hosts file
    lineinfile:
      path: /etc/hosts
      line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ hostvars[item]['ansible_fqdn'] }}\t{{ hostvars[item]['ansible_hostname'] }}"
    with_items: "{{ groups['all']}}"
  - name: Generate SSH key
    shell:  
      cmd: ssh-keygen -q -t rsa -N "" -f ~/.ssh/id_rsa
      creates: "~/.ssh/id_rsa"
  - name: Fetch root SSH key from node to master
    fetch:
      src: "/root/.ssh/id_rsa.pub"
      dest: "buffer/root/{{ansible_default_ipv4.address}}-id_rsa.pub"
      flat: yes
  - name: Copy root SSH key to all nodes' root user
    authorized_key:
      user: root
      key: "{{ lookup('file','buffer/root/{{ item }}-id_rsa.pub')  }}"
    when: item  != ansible_default_ipv4.address
    with_items: "{{ groups['all'] }}"
  - name: increase the soft and hard limits for the opened files on all nodes
    blockinfile:
      path: /etc/security/limits.conf
      insertbefore: '# End of file'
      block: |
        root soft nofile 2048
        root hard nofile 4096
        onapp soft nofile 2048
        onapp hard nofile 4096
  - name: Increase semaphore limits
    blockinfile:
      path: /etc/sysctl.conf
      block: | 
        kernel.msgmni = 1024
        kernel.sem = 250 256000 32 1024
