---
- hosts: all
  remote_user: root
  tasks:
  - name: update OS
    yum:
      name: '*'
      state: latest
  - name: Set hostname
    hostname:
      name: "{{ cp_hostname_long }}"
  - name: Insert CP's loopback address into /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "127.0.0.1\t{{ ansible_fqdn }}\t{{ ansible_hostname }}"
  - name: increase the soft and hard limits for the opened files on all nodes
    blockinfile:
      path: /etc/security/limits.conf
      insertbefore: '# End of file'
      block: |
        root soft nofile 2048
        root hard nofile 4096
        onapp soft nofile 2048
        onapp hard nofile 4096
  - name: Increase semaphore limits
    blockinfile:
      path: /etc/sysctl.conf
      block: | 
        kernel.msgmni = 1024
        kernel.sem = 250 256000 32 1024
