---
- hosts: all
  remote_user: root
  tasks:
#  - name: update OS
#    yum:
#      name: '*'
#      state: latest
  - name: Install OnApp repo
    command: rpm -Uvh http://rpm.repo.onapp.com/repo/onapp-repo-6.0.noarch.rpm
    register: command_result
    # if you see an error like 'package is already installed' but still want to proceed
    # then uncomment the line below
    failed_when: command_result.rc > 0 and 'already installed' not in command_result.stderr
  - name: Install CP installer
    yum:
      name: onapp-cp-install
      state: latest
  - name: Install OnApp
    command: /onapp/onapp-cp-install/onapp-cp-install.sh --ha-install --percona-cluster -a --accept-eula
  - name: Set hostname
    hostname:
      name: "{{ cp_hostname_long }}"
  - name: Insert all CPs in hosts file
    lineinfile:
      path: /etc/hosts
      line: "{{ ansible_default_ipv4.address }}\t{{ inventory_hostname }}\t{{ inventory_hostname_short }}"
  - name: increase the soft and hard limits for the opened files on all nodes
    blockinfile:
      path: /etc/security/limits.conf
      insertbefore: '# End of file'
      block: |
        root soft nofile 2048
        root hard nofile 4096
        onapp soft nofile 2048
        onapp hard nofile 4096
